# Generated by Django 4.1.2 on 2022-10-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0002_alter_sheet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
